# Generated by Django 2.2 on 2020-09-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='bio',
        ),
    ]
