# Generated by Django 3.1.1 on 2020-09-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address_line_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_line_2',
            field=models.CharField(max_length=100),
        ),
    ]
