# Generated by Django 3.1.1 on 2020-09-13 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200913_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
