# Generated by Django 3.1.1 on 2020-10-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201013_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(default='default.jpg', upload_to='property_images/'),
        ),
    ]
