# Generated by Django 3.1.1 on 2020-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201013_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='Occupation',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Doctor', 'Doctor'), ('Enterepreneur', 'Enterepreneur')], max_length=200),
        ),
    ]
