# Generated by Django 3.1.1 on 2020-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201014_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkpropertylist',
            name='bookmarked_properties',
            field=models.ManyToManyField(blank=True, to='users.Property'),
        ),
    ]
