# Generated by Django 3.1.1 on 2020-10-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201014_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(choices=[('', ''), ('Borivali', 'Borivali'), ('Kandivali', 'Kandivali'), ('Malad', 'Malad'), ('Goregaon', 'Goregaon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_size',
            field=models.CharField(choices=[('', ''), ('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='maritial_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10),
        ),
    ]
