# Generated by Django 3.1.1 on 2020-10-16 06:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201016_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
